subjects:
  genome: data/subjects/genome.fna
queries:
  proteins1: data/queries/proteins1.faa
  proteins2: data/queries/proteins2.faa

blast_evalue: 0.01
left_addendum: 100000
right_addendum: 100000
exonerate_percentage: 20
blosum: 45
pam: 200
cd_hit_threshold: 100
id_threshold: 35
sim_threshold: 55
overlap_percentage: 80
properties: $HOME/.jalview_properties
threads: 8
