subjects:
  genome1: data/subjects/genome1.fna
  genome2: data/subjects/genome2.fna
queries:
  proteins1: data/queries/proteins1.faa
  proteins2: data/queries/proteins2.faa

blast_evalue: 1e-4
left_addendum: 100000
right_addendum: 100000
exonerate_percentage: 20
blosum: 45
pam: 200
cd_hit_threshold: 99
sim_threshold: 50
properties: $HOME/.jalview_properties
threads: 4
