subjects:
  subject_1: data/subjects/subject_1.fna
  subject_2: data/subjects/subject_2.fna
queries:
  query_1: data/queries/query_1.faa
  query_2: data/queries/query_2.faa
  query_3: data/queries/query_3.faa

evalue: 1e-6
left_addendum: 1000
right_addendum: 1000
exonerate_percentage: 19
blosum: 62
refine: region
hsp: 3
strand: 3
pam: 160
stop_at_stop: 1
hssp_distance: 0
filter_met: 1
overlap_percentage: 70
properties: <path_to_properties_file>
best: a
pre_introns: 0
threads: 30
