subjects:
<<<<<<< HEAD
  csp: data/subjects/csp.fna
  gpe: data/subjects/gpe.fna
  hpl: data/subjects/hpl.fna
  egr: data/subjects/egr.fna
  pmi: data/subjects/pmi.fna
  ppr: data/subjects/ppr.fna
=======
  {genome1}: data/subjects/{genome1}.fna
  {genome2}: data/subjects/{genome2}.fna
>>>>>>> d6b6c438f1a28af08eaf2b9cb4cb6fa4d9b0ebad
queries:
  {proteins1}: data/queries/{proteins1}.faa
  {proteins2}: data/queries/{proteins2}.faa

blast_evalue: {num}
left_addendum: {num}
right_addendum: {num}
exonerate_percentage: {num}
blosum: {num}
pam: {num}
cd_hit_threshold: {num}
sim_threshold: {num}
properties: {path}
threads: {num}
