subjects:
<<<<<<< HEAD
  csp: data/subjects/csp.fna
  gpe: data/subjects/gpe.fna
queries:
  actin: data/queries/actin.faa
  beta_tubulin2: data/queries/beta_tubulin2.faa
  trp_channels: data/queries/trp_channels.faa
=======
  {genome1}: data/subjects/{genome1}.fna
  {genome2}: data/subjects/{genome2}.fna
queries:
  {proteins1}: data/queries/{proteins1}.faa
  {proteins2}: data/queries/{proteins2}.faa
>>>>>>> f180445a414874aa25de407e6b8ae57fa836f3ec

blast_evalue: {num}
left_addendum: {num}
right_addendum: {num}
exonerate_percentage: {num}
blosum: {num}
pam: {num}
cd_hit_threshold: {num}
sim_threshold: {num}
properties: {path}
threads: {num}
