subjects:
  csp: data/subjects/csp.fna
  gpe: data/subjects/gpe.fna
queries:
  actin: data/queries/actin.faa
  beta_tubulin2: data/queries/beta_tubulin2.faa
  trp_channels: data/queries/trp_channels.faa

blast_evalue: 1e-4
left_addendum: 100000
right_addendum: 100000
exonerate_percentage: 20
blosum: 45
pam: 200
cd_hit_threshold: 99
sim_threshold: 50
properties: $HOME/.jalview_properties
threads: 4
