subjects:
  genome1: data/subjects/genome1.fna
  genome2: data/subjects/genome2.fna
queries:
  proteins1: data/queries/proteins1.faa
  proteins2: data/queries/proteins2.faa

blast_evalue: {num}
left_addendum: {num}
right_addendum: {num}
exonerate_percentage: {num}
blosum: {num}
pam: {num}
id_threshold: {num}
sim_threshold: {num}
properties: {path}
threads: {num}
